### ISSUE TITLE
Add to lang PT_BR

### ISSUE THREAD

**Issue by FilhodoSenhor** [Xstar97/TXI#108]
Gostaria de que foce adicionado à língua portuguesa do Brasil, caso queira posso ajudar na tradução é só me dizer como! Adicione também um link de de download para as aplicações Busybox e Xpouse Installer recomendados, Jesus abençoei.

**Comment by Xstar97** [comment]
I vai voltar adicionar o recurso busybox app mais tarde ... no entanto, eu não posso fazer o mesmo para instalador Xposed desde a sua não está disponível no Google Play (seu contra as diretrizes do Google Play para oferecer aplicativos fora do Google Play.) Também estou trabalhando em um novo sistema de banco de dados para a minha ferramenta que está tomando um pouco mais que o normal ... então traduções terá que esperar um pouco mais também, mas ele estará disponível antes do lançamento público da nova ferramenta.
_______________________________________________
I will re add the busybox app feature later...however I cant do the same for xposed installer since its not available on google play(its against google play guidelines to offer apps outside of google play.) Also I am working on a new database system for my tool which is taking a bit longer than usual...so translations will have to wait a bit longer too, but it will be available before the public release of the new tool.

**Comment by FilhodoSenhor** [comment]
Entendo, não vi aqui uma parte onde contribuir para a tradução você poderia criar para que usuários interessados no projeto viessem a contribuir, poderia ajudar já que o App tem uma interface simples e poucos diálogos complexos, gostaria?

**Comment by Xstar97** [comment]
Sim ... no começo eu fiz, mas eu removi o ramo de tradução, porque eu não sou muito chegada com o texto na minha ferramenta e eu quero ter todo o texto disponível concluída ... que os usuários possam traduzir traduções / Update a partir do ramo de Tradução . em breve um novo ramo será recriado para fins de tradução.
_________________________________
Yes... at first I did, but I removed the translation branch because I am not quite finish with the text in my tool & I want to have all available text completed...so users can translate/update translations from the Translation branch. sometime soon a new branch will be recreated for translation purposes.

**Comment by Xstar97** [comment]
aqui está o link para o novo ramo
______
here's the link to the new branch
https://github.com/Xstar97/TXI/blob/translation/

**Comment by FilhodoSenhor** [comment]
Got it, your app is excellent worked well chegei installing Xpose yesterday, I did not have time to answer the last post, but now the surprise with the link was even better thank you, and I see no need for many other texts per hour, do as end said project and then see if something is missing, I will dedicate myself here at the new branch hope not as dificio is only support you who helped me with their love for the application and also thinking about the next with the same difficulties. Thank you Jesus continues to bless us.
---------------------------------------------------------------------------------------------------------------------

Entendi, sua app é otima funcionou bem chegei a instalar o xpose ontem, não tive tempo de responder o ultimo post, mas, agora a surpresa com o link foi ainda melhor obrigado, e não vejo necessidade de muitos outros textos por hora, faça como disse termine o projeto e depois vemos se falta algo, vou me dedicar aqui no novo ramo espero que não seja tão dificio é so um apoio a você que me ajudou com seu amor pela aplicação e pensando também no proximo com as mesmas dificuldades. Obrigado Jesus continue nos abençoando.

**Comment by FilhodoSenhor** [comment]
Got it, your App is great worked well got to install the Xposed yesterday, did not have time to answer the last post, but now the surprise with the link was even better thank you, and I see no need for many other texts per hour, do as end said project and then see if something is missing, I will dedicate myself here at the new branch hope it is not so difficult is just a support to you who helped me with their love for the application and also thinking about the next with the same difficulties. Thank you Jesus continues to bless us.

PS: the text formatting freaked out and made these big letters there wanted the standard.
---------------------------------------------------------------------------------------------------------------------
Entendi, sua App é ótima funcionou bem cheguei a instalar o Xposed ontem, não tive tempo de responder o ultimo post, mas, agora a surpresa com o link foi ainda melhor obrigado, e não vejo necessidade de muitos outros textos por hora, faça como disse termine o projeto e depois vemos se falta algo, vou me dedicar aqui no novo ramo espero que não seja tão difícil é só um apoio a você que me ajudou com seu amor pela aplicação e pensando também no próximo com as mesmas dificuldades. Obrigado Jesus continue nos abençoando.

PS: a formatação do texto pirou e fez estas letras grandes ai queria o padrão.
