### ISSUE TITLE
Marco no encontrado

### ISSUE THREAD

**Issue by Brivon1966** [Xstar97/TXI#19]
Hola tengo un Samsung galaxy s6 edge plus 5.1 ARM con las ROM SAMSUNG y no puedo instalar el marco para xposed lo va actualizar

Debug info:
 OS Version: 3.10.61-5962091(G928GUBU2AOJ4)
 OS API Level: 22
 Device: zenlte
 Model (and Product): SM-G928G (zenlteub)
 RELEASE: 5.1.1
 BRAND: samsung
 DISPLAY: LMY47X.G928GUBU2AOJ4
 CPU_ABI: arm64-v8a
 CPU_ABI2: 
 HARDWARE: samsungexynos7420
 MANUFACTURER: samsung

Extra Info: stack.trace does NOT exist

**Comment by Xstar97** [comment]
El dispositivo no está "ARM", pero arm64-V8A
El dispositivo es compatible, pero que investigará puede decirme qué error mensajes pop-up?

tendrá que instalar busybox con el fin de utilizar mi herramienta ... una próxima actualización requerirá ahora
___________________________________________________
Your device is not "arm" but arm64-v8a
Your device is supported, but I will investigate it can you tell me what error messages pop up?

you will need to install busybox in order to use my tool...a next update will require it now

https://play.google.com/store/apps/details?id=stericson.busybox

**Comment by Xstar97** [comment]
Did that fix your problem?
